name: dlv9
version: '1.4.1'
summary: Delve is a debugger for the Go programming language.
description: |
  Delve is a debugger for the Go programming language. 
  The goal of the project is to provide a simple, full featured debugging tool for Go.
  Delve should be easy to invoke and easy to use. Chances are if you're using a debugger, things aren't going your way.
  With that in mind, Delve should stay out of your way as much as possible.
confinement: strict
grade: stable
base: core18
architectures: [amd64]
parts:
  dlv:
    plugin: go
    go-importpath: ithub.com/go-delve/delve
    source: https://github.com/go-delve/delve/archive/v1.4.1.tar.gz
    source-checksum: sha256/6d9da41a18905c9819e33f475bf911facba1297674d2312ab5d7e2488fac685a
    source-type: tar
    build-packages:
    - gcc

apps:
  dlv:
    command: bin/dlv
    plugs: [ network, home]
